### ISSUE TITLE
Bundle using esbuild/webpack

### ISSUE THREAD

**Issue by JelleInfinity** [LuqueDaniel/vscode-language-renpy#116]
The [documentation](https://code.visualstudio.com/api/working-with-extensions/bundling-extension) recommends to bundle the extension. This reduces loading time and increases performance by minifying the source code.

Let's look into getting this setup. I have experience with webpack, but if esbuild is preferred that can be used.

**Comment by LuqueDaniel** [comment]
I didn't know it could be bundled. From what I see in the documentation, it seems simple to implement, and as you point out, there are exciting advantages. Regarding Esbuild or Webpack, I don't have much experience with either.

**Comment by JelleInfinity** [comment]
Then I'd say let's go for webpack. It seems like Esbuild is not as configurable.

I might do it a bit later, but I feel like this is a bit lower on my priority list rn.
