### ISSUE TITLE
Incorrect error for variable starting with two underscores

### ISSUE THREAD

**Issue by Numerlor** [LuqueDaniel/vscode-language-renpy#122]
The extension marks a name starting with two underscores as invalid
![](https://i.imgur.com/yK4qGsv.png)
but Ren'Py only reserves names starting with a single underscore [https://www.renpy.org/doc/html/reserved.html](https://www.renpy.org/doc/html/reserved.html#:~:text=Ren%27Py%20reserves%20all%20names%20beginning%20with%20a%20single%20underscore%20(_).%20Do%20not%20use%20names%20beginning%20with%20an%20underscore%2C%20as%20that%20may%20cause%20your%20game%20to%20break%20in%20future%20versions%20of%20Ren%27Py.).

**Comment by JelleInfinity** [comment]
Even though you are right that Ren'Py only reserves all names beginning with a single underscore (_). It also mentions you should not use underscores.

> Ren'Py reserves all names beginning with a **single** underscore (_). Do _**not** use names beginning with an underscore_, **as that may cause your game to break in future versions of Ren'Py**.

So I'm not sure if this should be fixed

**Comment by JelleInfinity** [comment]
@LuqueDaniel What do you think? Should it stay an error, maybe a warning or do we only test single _

**Comment by Numerlor** [comment]
> Even though you are right that Ren'Py only reserves all names beginning with a single underscore (_). It also mentions you should not use underscores.
> 
> > Ren'Py reserves all names beginning with a **single** underscore (_). Do _**not** use names beginning with an underscore_, **as that may cause your game to break in future versions of Ren'Py**.
> 
> So I'm not sure if this should be fixed

Considering double underscores mangle the name with the name of the module, I think the second sentence is specifically talking about the single underscore case. The chance getting a conflict with a renpy internal name with a name that's mangled and contains the module name should be practically non existent

**Comment by JelleInfinity** [comment]
Yeah, I think you're right about that.

Python does [mangle](https://stackoverflow.com/questions/13498151/python-double-underscore-mangling) variables with two underscores with the module.

I guess this can be changed to allow double underscores.
You could create a pull request if you'd like. Otherwise I'll post a fix as soon as I'm done with my current task.

**Comment by LuqueDaniel** [comment]
Good catch. That error should only be displayed when it starts with a `_`. And It should be a warning.
