### ISSUE TITLE
Setting `warnOnInvalidVariableNames` should not be an enum

### ISSUE THREAD

**Issue by LuqueDaniel** [LuqueDaniel/vscode-language-renpy#124]
The `warnOnInvalidVariableNames` option supports different levels (Error, Warning, and Disabled).

https://github.com/LuqueDaniel/vscode-language-renpy/blob/0885aef23a21be80465c5c1a63b9c1531e29b791/package.json#L122-L129

But a variable whose name is not valid should be an error. I think it doesn't make much sense that severity can be configured.

**Comment by rdurfee** [comment]
I believe I made this an enumeration in the configuration because a couple of people rather intensely disliked the feature. But I agree, it should an error.

**Comment by LuqueDaniel** [comment]
If the name is not valid, Ren'Py will treat it as an error and throw an exception. I understand that some users want to disable it, but turning it into a warning message doesn't seem to be useful.
