### ISSUE TITLE
[Suggestion] Clear existing *rpyc button

### ISSUE THREAD

**Issue by pjpollina** [LuqueDaniel/vscode-language-renpy#144]
Dunno if it's in the scope of what this plugin is going for but an easy button to clear out old rpyc files since they're hidden by default would be nice. In bash its as simple as running `find . -type f -name '*.rpyc' -delete`, which on one hand makes it kinda redundant but hey, why not?

**Comment by JelleInfinity** [comment]
Sounds cool. Not sure where you would place such a button though. One thing you can do for sure is add a command for it

**Comment by LuqueDaniel** [comment]
Yes, a command is the best option.

**Comment by rdurfee** [comment]
This is strongly not recommended.

The information in rpyc files is needed for upgrades and loading save files built with previous versions of your scripts. Deleting the files will break compatibility with save games and should only be done as a last resort. Force compile in the launcher is the preferred way to fix issues with rpyc files.

https://www.renpy.org/doc/html/build.html#the-old-game-directory
https://patreon.renpy.org/rpyc.html

**Comment by JelleInfinity** [comment]
In that case I think it would be best not to include this in the plugin. As to not give the idea to the user this is something that should be done.

**Comment by pjpollina** [comment]
I disagree, as long as it's documented with that message in mind there's no reason not to include it for people who face far more issues manually having to clear out old rpyc files than loading old saves. I doubt many people who use the VSCode command palette are types that would do something like that without understanding the implications.

Of course, that's just my opinion, I'll respect whatever Jelle and Luque decide is best for the plugin.

**Comment by KiloOscarSix** [comment]
How about a middle ground, a command that detects unlinked `.rpyc` files (rpyc files that don't have a corresponding rpy file) and automatically creates/moves the [old game directory](https://www.renpy.org/doc/html/build.html#the-old-game-directory) ?

**Comment by a2937** [comment]
Hello. May I take on adding the command that migrates old .rpyc files to the old game directory?

**Comment by LuqueDaniel** [comment]
@a2937 Sure! There is no one working on this feature. Thank you for contributing!
