### ISSUE TITLE
Python script to add VSCode no longer needed 

### ISSUE THREAD

**Issue by JelleInfinity** [LuqueDaniel/vscode-language-renpy#145]
Am I correct in that [this script](https://github.com/LuqueDaniel/vscode-language-renpy/blob/master/Visual%20Studio%20Code.edit.py) is no longer needed since @renpytom has integrated it into the launcher already?

If that's the case I would suggest removing the file and the section in the readme

**Comment by LuqueDaniel** [comment]
It was added so that users with older versions of Ren'Py could integrate the editor with their projects. 

Should we keep it? maybe we could move it to a code block inside the readme.

**Comment by JelleInfinity** [comment]
In that case we should at least edit the readme to make it clear this is intended for older users

**Comment by renpytom** [comment]
I'd suggest waiting for the final release of 7.5, when that happens.

**Comment by LuqueDaniel** [comment]
Ok, when version 7.5 is released we'll edit the readme to clarify that it's only required in versions <7.5.
