### ISSUE TITLE
[Pre-Release] [Bug] Issue with syntax highlighting inside script after one-line python statement

### ISSUE THREAD

**Issue by KiloOscarSix** [LuqueDaniel/vscode-language-renpy#164]
The easiest way to describe the issue is with a screenshot:
![image](https://user-images.githubusercontent.com/26691547/178527599-69196328-6e82-4dcf-ab09-c29efc1caecd.png)

After the `$ variable = True` statement, all syntax highlighting is gone, except string highlighting
Highlighting returns after next menu choice

**Comment by JelleInfinity** [comment]
Hi, thanks for the bug report. Could you send a screenshot of the syntax scope applied at `$ v2_nora_clue_camping = True` and the scope at `$ reputation.add_point...`

You can enable the scope inspector using https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector
