### ISSUE TITLE
Incorrect syntax highlighting on string concatenation with text tags

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#170]
### Extension version

2.1.1

### Issue description

![image](https://user-images.githubusercontent.com/22531674/179371734-59b4e7e7-1886-45af-a97c-31f58217b334.png)

As shown in the image, the `+ quip +` in both `say` calls are highlighted as strings despite not being within quotation marks.

### Scope inspector screenshots

![image](https://user-images.githubusercontent.com/22531674/179371748-b3c66aad-8061-43ae-92c0-85ce64033237.png)
![image](https://user-images.githubusercontent.com/22531674/179371751-12a10060-d51b-4bee-964b-2bccd2792714.png)

### Code

```renpy
label test:
    $ quip = "some quiplist choice"
    $ renpy.say(m, "{cps=*3}" + quip + "{/cps}")

    python:
        renpy.say(m, "{cps=*3}" + quip + "{/cps})

    return
```

**Comment by JelleInfinity** [comment]
Awesome, thanks for this. That makes the issue a lot more clear. I'm currently unable to check myself. Could you tell me if this also happens outside of python blocks/$ lines

**Comment by multimokia** [comment]
Sure.
![image](https://user-images.githubusercontent.com/22531674/179411283-a37d8620-4e08-4af3-bc99-7574924c98de.png)

In this case the closing tag not being present is a typo, but we see the behaviour is still present, and will span multiple lines.
![image](https://user-images.githubusercontent.com/22531674/179411321-d004fee1-5155-4d05-94e8-4a258ca9552b.png)
