### ISSUE TITLE
Don't overwrite existing "files.exclude" setting by default [Bug?/Suggestion]

### ISSUE THREAD

**Issue by pjpollina** [LuqueDaniel/vscode-language-renpy#172]
On its own it's fine, like the auto-generated exclusion is pretty swell, but the fact that it overwrites any additions you make to the file every time you reopen the editor is really annoying. I know you can turn it off in the plugin settings, but surely there's a way to both keep the generation without erasing additional settings, yeah?

**Comment by JelleInfinity** [comment]
Good point. I think it would overwrite it in some cases. Let's get that fixed :)

**Comment by pjpollina** [comment]
Update on this, I believe the issue is in this function in extension.ts:
```typescript
function updateShowCompiledFilesConfig(hide: boolean) {
    const config = workspace.getConfiguration("files");
    config.update("exclude",
    { "**/*.rpyc": hide, "**/*.rpa": hide, "**/*.rpymc": hide, "**/cache/": hide }, ConfigurationTarget.Workspace);
}
```
My guess is that `config.update`, at least when called in this way, completely replaces the existing `"files.exclude"` hash (sorry if that's the wrong term I'm mostly a Rust/Ruby guy haha), disregarding any additional fields that have been added by the user.

Testing it in multiple projects with multiple configurations, a settings.json like this:
```json
{
  "files.exclude": {
    "**/*.txt":   true,
    "**/*.bak":   true,
    "**/*.rpyc":  true,
    "**/*.rpyb":  true,
    "**/*.rpymc": true,

    "**/saves":   true,
    "**/cache":   true,
    "**/tl":      true,
  },

  "editor.tokenColorCustomizations": {
    "comments": "#297E",
  }
}
```

will get turned into this:

```json
{
  "files.exclude": {
    "**/*.rpyc": true, # False if the setting is turned off
    "**/*.rpa": true,
    "**/*.rpymc": true,
    "**/cache/": true
  },

  "editor.tokenColorCustomizations": {
    "comments": "#297E",
  }
}
```

Every time VSCode reloads. I don't really have the time at the moment get the runtime and everything set up to test for a solution, so I figured if anyone was interested in fixing this before I can I'd throw in my ideas.

**Comment by JelleInfinity** [comment]
Sorry for the late reply. That's indeed the issue. Feel free to make a merge request.

I think (I'll look it up in a sec) there is an example of how that could be done in the same file somewhere
