### ISSUE TITLE
Missing Color Preview Widget

### ISSUE THREAD

**Issue by Kiaazad** [LuqueDaniel/vscode-language-renpy#178]
Today I've updated my VSCodium and installed your latest Renpy extension, the document colors didn't show, downgraded to 2.0.12, it fixed the problem, Not sure if the same happens on VSCode too,

**Comment by LuqueDaniel** [comment]
What version of the extension did you have before downgrading? Our latest stable version is 2.0.12.

**Comment by Kiaazad** [comment]
Ah, sorry, mixed the versions, I've downgraded to 2.0.11

**Comment by LuqueDaniel** [comment]
I can't reproduce it, using 2.0.12, VSCodium 1.69.2 (only with Ren'Py extension installed).

![imagen](https://user-images.githubusercontent.com/1286535/182665891-da8e8ab3-b025-45c5-ad35-805a6128991f.png)

**Comment by Kiaazad** [comment]
Can be because of a difference between the windows and Linux OS
![image](https://user-images.githubusercontent.com/33455007/182669449-96889c30-2155-4b14-890c-8c0c85889454.png)
![image](https://user-images.githubusercontent.com/33455007/182669591-98d54509-6218-4ec1-adf6-62f135178228.png)
![image](https://user-images.githubusercontent.com/33455007/182669642-a27c4e2d-b030-48db-a45b-2b797bb3c9af.png)

**Comment by Kiaazad** [comment]
tried on another windows pc, got the same result

**Comment by JelleInfinity** [comment]
Hmm, that's very interesting. I don't see anything in the change list right away that could cause this bug.

Would you mind trying the pre-release version and see if it still happens on the development branch?

**Comment by JelleInfinity** [comment]
The one thing I can see right now that is possibly, (but unlikely) the cause is the upgrade to a new engine version

**Comment by Kiaazad** [comment]
Sure, I can give it a try, is there a guide I can follow to install the pre-release version? Do I download and put the files into one of the folders?

**Comment by JelleInfinity** [comment]
It should be available through the normal way you install the extension

**Comment by Kiaazad** [comment]
I've searched renpy in the extension tab of vscodium and installed the only version appeared. Can't spot any option for different versions.
The install other versions just shows a list of older versions. You have to hold my hand through the process. I'm not that familiar with vscode and using vscodium makes things a bit complicated since I can't simply click the website's button to install.

**Comment by Kiaazad** [comment]
Alright, managed to manually download 2.1.1 and install  in vsix way. The color previews are missing on this version as well.

**Comment by JelleInfinity** [comment]
Ah good. I wasn't sure how to do it since I've never used codium so I had to look it up.

For future reference; 

```
You can download the .vsix on the github page of each extensions
codium --install-extension myextension.vsix
```

**Comment by JelleInfinity** [comment]
> The color previews are missing on this version as well.

Good to know. I'll see if I can figure out why

**Comment by LuqueDaniel** [comment]
The last time I checked OpenVSX doesn't support publishing pre-release versions.

**Comment by Kiaazad** [comment]
Alright, let me know if you need a tester.

**Comment by LuqueDaniel** [comment]
I've tested it on Windows with VSCode and it works. Is it related to VSCodium on Windows? It is weird.

**Comment by JelleInfinity** [comment]
Yeah, maybe my guess isn't too far off then. Since codium would use a different code base I presume

> the cause is the upgrade to a new engine version

**Comment by JelleInfinity** [comment]
@LuqueDaniel Are you able to build a custom .vsix file for @Kiaazad to test were the vscode engine version is put back to `^1.50.0`.

I would like to have that ruled out as a possibility before I start digging through the code for hours 🤣

**Comment by Kiaazad** [comment]
since VSCodium is the VSCode source sans Microsoft telemetry, there can be a slight difference between the builds, one of them might be lagging behind in releasing the new version.

**Comment by LuqueDaniel** [comment]
@JelleInfinity No problem, I'll do that build!

**Comment by JelleInfinity** [comment]
So quick update. I was trying to find some new samples for `registerColorProvider` to see if the API changed between engine versions. 
Something that bothers me thos, is that https://github.com/microsoft/vscode-extension-samples doesn't seem to use the function anywhere.

This leads me to believe that this is in fact an outdated function, but I haven't found it's replacement yet.

**Comment by LuqueDaniel** [comment]
@Kiaazad Here is the build.

[languague-renpy_testbuild.zip](https://github.com/LuqueDaniel/vscode-language-renpy/files/9254909/languague-renpy_testbuild.zip)

**Comment by Kiaazad** [comment]
tried the test build, the color previews are missing.

**Comment by LuqueDaniel** [comment]
The new build contains changes from #179 

[language-renpy_2.0.13-testbuild.vsix.zip](https://github.com/LuqueDaniel/vscode-language-renpy/files/9257977/language-renpy_2.0.13-testbuild.vsix.zip)

**Comment by Kiaazad** [comment]
The color previews are still missing.
![image](https://user-images.githubusercontent.com/33455007/182802976-409cb5a1-c67f-4d1e-83c9-ddd87563045e.png)

**Comment by JelleInfinity** [comment]
That's unfortunate. But this does make me think a change in the code caused this to break. I'll look more at it when I find some time.

**Comment by Kiaazad** [comment]
There's no hurry, the older version works fine. We should keep an eye on it in though, case the same change would later appear in the VSCode as well.

**Comment by LuqueDaniel** [comment]
Tested on Windows with VSCodium (Only the Ren'Py extension is installed.)

![imagen](https://user-images.githubusercontent.com/1286535/182808252-92ba8972-d69a-4475-902f-25cc92c4a139.png)

```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-19T02:38:21.590Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by JelleInfinity** [comment]
@Kiaazad Does this only happen in that specific file?

For example does it work if you only put this in the file
`image red = Solid("#FF0000FF")`

**Comment by Kiaazad** [comment]
It seems to be the same in all files, any type of defining a color.

**Comment by JelleInfinity** [comment]
@LordTolaboon IIRC, for this specific case the extension fails to display the color because you have it written in this specific way.

Not to say that it shouldn't be resolved, but could you confirm this is the case?

**Comment by LuqueDaniel** [comment]
I've tried the code from Ren'Py's tutorial. Written that way it works.

![imagen](https://user-images.githubusercontent.com/1286535/200180317-3270f22b-acf7-439d-8678-f26b34a54920.png)

**Comment by JelleInfinity** [comment]
Ah, I see. In that case I'm not sure what's up. Maybe same problem as above, but if we can't repro it, it will be hard to solve

**Comment by LuqueDaniel** [comment]
> Ah, I see. In that case I'm not sure what's up. Maybe same problem as above, but if we can't repro it, it will be hard to solve.
> 
> @LuqueDaniel do you also have the python extensions installed? Unlikely, but they might interfere somehow?
> 
> I also noticed the file has 'utf-8 with bom' encoding. Maybe that's the issue?

When it was first reported I tried with and without the Python extension and could not reproduce it. I've also tried to change the encoding and it doesn't affect it.

@LordTolaboon Do you have the 'Editor: Color Decorators` option enabled?

**Comment by LordTolaboon** [comment]
@LuqueDaniel 
> Is the 'Editor: Color Decorators` option enabled?

Yes, it's enabled. In the meantime, I have found out that the color display works perfectly fine in some scripts. I found out yesterday as I worked in an older script and tested the qestion of @JelleInfinity  directly.

@JelleInfinity 
> As the only line in the file and seeing if it does show up then?

In some scripts it shows up
![Screenshot 2022-11-11 072652](https://user-images.githubusercontent.com/117577342/201277498-684159fe-fd44-4077-afc5-5b0ed1896b5d.png)
and in some scripts it doesn't.
![Screenshot 2022-11-11 072510](https://user-images.githubusercontent.com/117577342/201277539-b222b422-862a-4f4b-9fef-77bdf0aff28a.png)

In first case I copied your code in script.rpy of the Tutorial of Ren'Py. But I had this in other cases too. The second screenshot is from an old script of me where I copied this code into. So I've tested around and it seems random to me in which files it worked and in which not. I can't find any pattern.

**Comment by JelleInfinity** [comment]
Could be something with your text file. Something like the encoding or the line ending settings. Check the bottom right corner in VSCode and compare the files that work against the ones that don't

**Comment by LordTolaboon** [comment]
Hi again,

I was on a business trip so I can't watched and answered the last days. I've tested around a little bit and I've found out that I can't see the colors if I open the rpy file with Ren'Py Launcher. If I open the same file directly with Windows option "Open with Visual Studio" the colors appears.

**Comment by JelleInfinity** [comment]
Ahh, that's interesting.. Well that might give us a clue as to what's going wrong. I might take a look soon ish, super busy lately

**Comment by LuqueDaniel** [comment]
I tested it and was able to reproduce it. The color widget is not shown if I open a script from the Ren'Py launcher. However, it does show when opening the entire project from the launcher. However, it does show up when opening the project from the launcher.

This also applies when opening a Ren'Py script from VSCode or using the `code` command.

I hadn't thought about this until now but... The extension is only activated by the `workspaceContains:**/*.rpy` [event](https://code.visualstudio.com/api/references/activation-events#workspaceContains), so opening a file doesn't activate the extension 🤣. So we have to add also other events e.g. [`onLanguage`](https://code.visualstudio.com/api/references/activation-events#onLanguage).

https://github.com/LuqueDaniel/vscode-language-renpy/blob/dc4f34467d72c0998b45ffb8d9e2ecec4b06a167/package.json#L37-L39

**Comment by JelleInfinity** [comment]
Oh really, had no idea that vscode doesn't consider it a workspace when opening single files. That makes a lot of sense..
