### ISSUE TITLE
I get infinity status "Initializing Ren'Py static data..."

### ISSUE THREAD

**Issue by maLikiz** [LuqueDaniel/vscode-language-renpy#180]
### Extension version

v2.0.12

### Issue description

I get infinity status "Initializing Ren'Py static data..." Because of this, I lose the opportunity for a comfortable walk on the project
Is there any way I can track this error to find out exactly what the problem is.

I tried reinstalling the extension and after I tried run the command `renpy.refreshNavigationData`, I got the error message:
![image](https://user-images.githubusercontent.com/4878139/182741560-c9532df9-1f76-41f5-927f-2d46a748a214.png)

Error after executing the command `renpy.refreshNavigationData`:
![image](https://user-images.githubusercontent.com/4878139/182741695-9e80358a-863f-4444-a3bb-9b6e29538188.png)

After executing the `renpy.refreshDiagnostics` command, nothing happens.

### Scope inspector screenshots

![image](https://user-images.githubusercontent.com/4878139/182742251-d245e567-93af-4caf-835e-a2ad057aadbb.png)

### Code

--

**Comment by maLikiz** [comment]
I tried switching to the preview version of this extension and it solved my problem.

**Comment by develephant** [comment]
Just wanted to echo what @maLikiz said. Same issue for me as well and Pre-Release solved it.

Runninng on Win11.

-dev

**Comment by duckdoom4** [comment]
I'm going to close this assuming the issue will be solved by swapping to pre-release
