### ISSUE TITLE
Incorrect syntax highlighting for `scene expression "X"`

### ISSUE THREAD

**Issue by Booplicate** [LuqueDaniel/vscode-language-renpy#182]
### Extension version

2.1.1

### Issue description

`scene expression` with a string is missing syntax highlighting for strings.

### Scope inspector screenshots

![Capture](https://user-images.githubusercontent.com/53382877/185836801-fcaef6a2-df29-40de-bb8f-a6b7cb2d5f9f.PNG)

### Code

```renpy
scene expression "/path/here.png"
```

**Comment by Booplicate** [comment]
Just FYI
```renpy
scene expression "/path/here.png"
```
works fine.

**Comment by JelleInfinity** [comment]
Thanks for the bug report. I'll look at it when I find the time. Have been extremely busy lately.

Tho feel free to have a look and create a merge request. You could compare the two [in this file here](https://github.com/LuqueDaniel/vscode-language-renpy/blob/develop/syntaxes/renpy.tmLanguage.json#L212) and see if you can spot the issue.

(It might also be as simple as swapping the include order of some patterns)

Any help would be greatly appreciated :)

**Comment by Booplicate** [comment]
Oh, I think you're right, it's just missing a pattern, easy to fix.
