### ISSUE TITLE
Missing syntax highlighting for dataclasses and class references

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#183]
### Extension version

2.1.1

### Issue description

When creating dataclasses, fields and references to classes aren't highlighted, but instead are shown in the default color (as if they were being handled by a python 2 syntax highlighter)
![image](https://user-images.githubusercontent.com/22531674/186474290-442b969c-9b3f-47c8-bf96-35cd5c272a94.png)

As well, the `id` field is colored in gold due to the builtin function.

Loading the file as explicitly python displays the following:
![image](https://user-images.githubusercontent.com/22531674/186474184-861d6da0-7f44-4689-8403-2a63bf39ea42.png)

Ideally it'd be nice for the extension to be able to render classes like these similarly

### Scope inspector screenshots

![image](https://user-images.githubusercontent.com/22531674/186474372-bff7b54d-0dd6-455f-bacc-eb59887ef3ae.png)
![image](https://user-images.githubusercontent.com/22531674/186474423-57dff5c2-5d2d-4c8c-9f51-3b7072f05e93.png)

### Code

```renpy
init python:
    @dataclass
    class LatLonPair:
        lon: float,
        lat: float

    @dataclass
    class SimpleWeatherInfo:
        id: int,
        main: str,
        description: str,
        icon: str
```

**Comment by JelleInfinity** [comment]
Hmm, that's interesting. It should be the same.. I might have a look later, see if I can spot the issue
