### ISSUE TITLE
[Bug] - `files.exclude` is always updated even when renpy.excludeCompiledFilesFromWorkspace is false

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#195]
Would it be possible to make it so we can opt out of the automatic generation of `files.exclude` in local settings?

If I keep `"renpy.excludeCompiledFilesFromWorkspace": false,` in my main `settings.json` file, I notice every time I load a project, there's untracked changes to my local `settings.json` as the extension keeps adding the compiled files to it, even if the patterns are all set to off.

However this behaviour seems redundant as there's no need to add them there.
Personally I'd love it if this wouldn't keep being re-added!

**Comment by LuqueDaniel** [comment]
It will be enough to modify the conditional to check the value of `renpy.excludeCompiledFilesFromWorkspace`.

https://github.com/LuqueDaniel/vscode-language-renpy/blob/7fab9218640384ed8fb473045d67fe8f5dd8aaa0/src/extension.ts#L77-L81

**Comment by multimokia** [comment]
Can confirm this is still on latest

**Comment by LuqueDaniel** [comment]
Yes, because what I fixed was the overwriting of other values that may have `files.exclude` #172 .

I'll change it so that it only writes the values in case the `renpy.excludeCompiledFilesFromWorkspace` option is enabled.

**Comment by multimokia** [comment]
Awesome, thank you!

**Comment by JelleInfinity** [comment]
@LuqueDaniel We should compare the values in the config to the new values. Cus we need to make sure that if 'hide' is set to false, it also updates the config values
