### ISSUE TITLE
Float parsing changed in prerelease

### ISSUE THREAD

**Issue by Gouvernathor** [LuqueDaniel/vscode-language-renpy#202]
In the prerelease version, floats starting with a dot are colored incorrectly in some cases, including in pause statements.
![image](https://user-images.githubusercontent.com/44340603/188342019-161ce4db-4709-4c6f-ac0b-a3960f975aca.png)
This is not the case in the normal release, where that `.5` is as green-ish as the `1`. And it's also not the case if writing `0.5`.

**Comment by duckdoom4** [comment]
Should be fixed with that commit. A new release with that fix will be posted soon :)
