### ISSUE TITLE
Wrong string highlighting

### ISSUE THREAD

**Issue by Gouvernathor** [LuqueDaniel/vscode-language-renpy#231]
### Extension version

2.1.2

### Issue description

The string style should apply inside the parentheses but outside the brackets, and not overflow over the following lines.

### Scope inspector screenshots

![image](https://user-images.githubusercontent.com/44340603/212558549-85d32b4d-9933-45f1-a240-7d7d40746d4d.png)

### Code

https://github.com/renpy/renpy/blob/master/launcher/game/translations.rpy#L332-L348
```rpy
screen extract_dialogue:

    frame:
        style_group "l"
        style "l_root"

        window:

            has vbox

            label _("Extract Dialogue: [project.current.display_name!q]")

            add HALF_SPACER

            frame:
                style "l_indent"
                xfill True
```

**Comment by Gouvernathor** [comment]
I found the trigger point : a screen-language `label` whose string contains a colon.
It's probably the code for the script `label` overflowing into screen language inproperly.

**Comment by duckdoom4** [comment]
Thanks that helps a lot. I'll have a look in a bit :)

**Comment by duckdoom4** [comment]
Okay, I found the issue. 
I think the root cause for this, is that screen language has different syntax for labels.
You you confirm that under normal renpy syntax `label _(":")` would be invalid?

**Comment by Gouvernathor** [comment]
Yep, in script that's invalid cause label parses a name and not an expression (and a colon too)

**Comment by duckdoom4** [comment]
I've pushed a change that fixes this issue, by separating the screen languague syntax from the default renpy syntax. Just like I had done with ATL.

https://github.com/LuqueDaniel/vscode-language-renpy/pull/250

Unfortunately I don't have more time right now to implement the entire feature set of the screen language, but feel free to report all missing features or bugs you come across and I will fix it when I find the time :)

**Comment by LuqueDaniel** [comment]
> @LuqueDaniel Could you make a new pre-release build with #250 included?

Sure, this afternoon when I have a moment I'll make it 👍

**Comment by LuqueDaniel** [comment]
Done! New pre-release 2.1.3

**Comment by Gouvernathor** [comment]
Works fine on the two test cases on my end, now 👌
