### ISSUE TITLE
files.exclude settings keep getting overwritten

### ISSUE THREAD

**Issue by Gouvernathor** [LuqueDaniel/vscode-language-renpy#245]
When settings.json doesn't exist or doesn't contain the rules, the extension adds these :
```json
"files.exclude": {
    "**/*.rpyc": true,
    "**/*.rpa": true,
    "**/*.rpymc": true,
    "**/cache/": true
}
```
This is only fair. However, I prefer to see compiled files on some projects, so I manually set the rules to this :
```json
"files.exclude": {
    "**/*.rpyc": false,
    "**/*.rpa": true,
    "**/*.rpymc": false,
    "**/cache/": true
}
```
For some reason, the extension cannot accept my override and keeps reverting these to true at every boot. It gets _very_ tedious to have to change these manually every time I have to delete a file.

**Comment by LuqueDaniel** [comment]
It will be resolved in the next release. Ref #238

**Comment by Gouvernathor** [comment]
Is it normal that the prereleases still include this ?

**Comment by LuqueDaniel** [comment]
No, it is not normal. I just tested with version 2.1.6-pre-release, enabling and disabling the `renpy.excludeCompiledFilesFromWorkspace`. The previous rules in `files.exlcudes` are not overwritten and the existing sequence is respected. If one of the rules already exists its value is not overwritten either.

On the other hand, if the setting is enabled and the project doesn't have a `.vscode/settings.json` file or the key `files.exclude` doesn't exist, the extension will add it and exclude the files.

**Comment by Gouvernathor** [comment]
Yeah, it seems to work, must have been a mistake on my end (mixing a project where I had disabled it and one where I had not, probably). Sorry about that.
