### ISSUE TITLE
[BUG] - Commands not found

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#25]
Just installed the new update for the plugin and wanted to note an issue, not quite sure why it's happening though as the code looks right in how it provides them:

When trying to compile navigation data:
![image](https://user-images.githubusercontent.com/22531674/137637316-4278fb46-b71c-48d7-976c-c54b4adeec87.png)

Refresh diagnostics:
![image](https://user-images.githubusercontent.com/22531674/137637330-4e600083-0beb-4998-b4c7-6130a43092f2.png)

And refreshing navigation data:
![image](https://user-images.githubusercontent.com/22531674/137637373-7448310a-8ccb-42ff-afec-c88d2b0ae55c.png)

Additionally my tests on #21, interestingly only seemed to run from the extension host window, but loading up a general rpy file does not seem to provide any highlighting or renpy info.

Especially for the repository linked on that PR, this would be amazing if it could be fixed!

**Comment by rdurfee** [comment]
I believe this happens when the navigation.json file is not found, i.e., the game hasn't been compiled.

I'm working on a commit right now that should fix this.

**Comment by AVagueNumberOfHumans** [comment]
> I believe this happens when the navigation.json file is not found, i.e., the game hasn't been compiled.
> 
> I'm working on a commit right now that should fix this.

I hope it fixes this command not being found, I rather enjoy Copy+Paste.
![image](https://user-images.githubusercontent.com/51864897/137645892-7b9710b3-62a0-456c-bb8f-e9ca4b2fc930.png)

**Comment by multimokia** [comment]
> 
> 
> > I believe this happens when the navigation.json file is not found, i.e., the game hasn't been compiled.
> > I'm working on a commit right now that should fix this.
> 
> I hope it fixes this command not being found, I rather enjoy Copy+Paste. ![image](https://user-images.githubusercontent.com/51864897/137645892-7b9710b3-62a0-456c-bb8f-e9ca4b2fc930.png)

This doesn't seem to be referenced in this plugin, I think this might be something to do with another plugin you're using

**Comment by LuqueDaniel** [comment]
> 
> 
> > I believe this happens when the navigation.json file is not found, i.e., the game hasn't been compiled.
> > I'm working on a commit right now that should fix this.
> 
> I hope it fixes this command not being found, I rather enjoy Copy+Paste. ![image](https://user-images.githubusercontent.com/51864897/137645892-7b9710b3-62a0-456c-bb8f-e9ca4b2fc930.png)

@AVagueNumberOfHumans Try disabling the extension, if the command works again after that, open a new issue.
