### ISSUE TITLE
Embedded Python one-liner in layout style property causes using wrong scope in next style statement

### ISSUE THREAD

**Issue by FaceCrap** [LuqueDaniel/vscode-language-renpy#270]
### Extension version

2.1.5 pre-release

### Issue description

Embedded Python code in layout style property causes highlighting to continue into the next style statement, still using the scope for the embedded code. i.e., instead of switching to `keyword.python.renpy renpy.source` it keeps using `meta.embedded.line.python source.renpy` until after a next style statement does not use the same layout construct. 
Meaning, the first following style statement will be incorrectly highlighted, and as long as that statement does not use the same `layout` construct, the style statement thereafter will be highlighted correctly. However, if the next one also uses the same layout construct, highlighting will only be correct again after a style statement without that layout construct. (see below screenshot)

![codesample](https://user-images.githubusercontent.com/95778718/221332909-0ad21f9e-c796-435b-ae28-c5a590af36fe.png)

( I have no idea what GitHub does with images, but the coloring is way off. The color of strings should be a light cyan, but it appears as almost white )

After looking in `renpy.tmLanguage.json`, it seems the culprit lives at line 1107... but I might be interpreting this incorrectly. Seeing the name of the block and there being a `begin` and `end` regexp at lines 1094 and 1123 respectively, that these somehow also open the possibility of it triggering on such constructions.

```json
    "menu-option": {
      "contentName": "meta.block.menu-option.renpy",
      "begin": "^([ \\t]+)?((?:\".*\")|(?:'.*')|(?:\"\"\".*\"\"\"))[ \\t]*(.+)?(:)",
      "beginCaptures": {
        "1": { "name": "punctuation.whitespace.menu-option.leading.renpy" },
        "2": {
          "name": "meta.menu-option.renpy",
          "patterns": [{ "include": "#strings" }]
        },
        "3": {
          "name": "meta.embedded.line.python",
          "patterns": [
            { "include": "source.renpy.python#function-arguments" },
            {
              "comment": "if condition",
              "match": "\\b(if)[ \\t]+(.+)?",                                            # <-- this one?
              "captures": {
                "1": { "name": "keyword.control.conditional.renpy" },
                "2": {
                  "patterns": [{ "include": "source.renpy.python#expression-bare" }]
                }
              }
            },
            {
              "match": "[^ \\t]+",
              "name": "invalid.illegal.unexpected-characters-in-menu-arguments.renpy"
            }
          ]
        },
        "4": { "name": "punctuation.section.menu-option.begin.renpy" }
      },
      "end": "^(?=(?!\\1)[ \\t]*[^\\s#]|\\1[^\\s#])",
      "patterns": [{ "include": "#statements" }, { "include": "#expressions" }]
    },
```

I assume that this is primarily intended for menu choices, where an `if <expression>` controls the visibility of a choice?
If so, would not be the end dictated by the presence of a `:` colon?

### Scope inspector screenshots

![scope](https://user-images.githubusercontent.com/95778718/221332960-e7cfe9db-4878-4e0e-95c1-c0a85d3bdda8.png)

### Code

```renpy
style history_text:
    xpos gui.history_text_xpos
    ypos gui.history_text_ypos
    xanchor gui.history_text_xalign
    xsize gui.history_text_width
    min_width gui.history_text_width
    text_align gui.history_text_xalign
    layout ("subtitle" if gui.history_text_xalign else "tex")

style history_label:
    xfill True

style history_label_text:
    xalign 0.5
```

**Comment by duckdoom4** [comment]
Hi again, thanks for the bug report. :)

I didn't take the time to read everything yet, but the 'style block' highlighting has been added very recently and I didn't have the time to implement everything properly (a lot is missing).

That said, thanks for looking into it. I will read everything you posted properly in a bit. If you think you are able to fix it, we are very open to pull requests :)

**Comment by FaceCrap** [comment]
> That said, thanks for looking into it. I will read everything you posted properly in a bit. If you think you are able to fix it, we are very open to pull requests :)

Ha! I wish 😄 After looking at the JavaScript and testing the regexp's in Expresso, I probably am not even correct about the bit of code responsible.

**Comment by duckdoom4** [comment]
I looked at it a bit closer now, it seems
 `layout ("subtitle" if gui.history_text_xalign else "tex")`
Starts a python embed line that's never closed. Not sure about what causes it yet. I'd have to debug it properly.

To figure it out I'd need to look at the scope inspector and hover over the line I mentioned and see where it starts the scope. That should give me an idea about where to look.

**Comment by duckdoom4** [comment]
Got it, #279 should fix the issue :)
