### ISSUE TITLE
`\\"` and `\\'` aren't recognized as ending a string

### ISSUE THREAD

**Issue by Gouvernathor** [LuqueDaniel/vscode-language-renpy#276]
### Extension version

2.1.5

### Issue description

![image](https://user-images.githubusercontent.com/44340603/222977865-3f2350e3-38e0-44f8-8527-338267527aed.png)
The string given in `exclude` terminates with the single quote at the end of the line, it should not span the following line(s).

### Scope inspector screenshots

![image](https://user-images.githubusercontent.com/44340603/222977962-b0e1a8bb-199b-4e24-86ae-8efa90997d88.png)

### Code

```rpy
screen a():
    input:
        exclude "\\"
        # some other line "
```

**Comment by duckdoom4** [comment]
Thanks for the report! #277 should fix this issue :)
