### ISSUE TITLE
Menu option conditions parsing as an error

### ISSUE THREAD

**Issue by Gouvernathor** [LuqueDaniel/vscode-language-renpy#292]
![image](https://user-images.githubusercontent.com/44340603/235323916-4a330d83-f7e2-4a63-b28d-d481e572a2ae.png)
See the red part, which has no real reason to be red since it compiles without a problem.
The red highlighting persists when putting the expression in parentheses, which is even more surprising to me.

**Comment by duckdoom4** [comment]
Thanks for the bug report. I'll look into it when I get back from my holiday trip
