### ISSUE TITLE
conflict with Code Spell Checker extension 

### ISSUE THREAD

**Issue by Kiaazad** [LuqueDaniel/vscode-language-renpy#3]
when enabled the spell check doesn't detect mistakes in rpy files.
awesome work by the way ^_^

**Comment by LuqueDaniel** [comment]
Hello and thanks ^^

Follow the next image:
![enable_renpy](https://user-images.githubusercontent.com/1286535/54454343-875a1500-4759-11e9-9b54-7254220560bf.png)

Click on status bar Spell Check > FILE INFO TAB > Spell Checker Enabled for file type (renpy)

**Comment by Kiaazad** [comment]
can't believe I missed the tabs, thank you ^_^
