### ISSUE TITLE
Some colors chaged and I don't now why

### ISSUE THREAD

**Issue by JoaoGW7** [LuqueDaniel/vscode-language-renpy#329]
### Extension version

2.2.0

### Issue description

When I first started the visual studio today, then I was required to reaload the studio, I did it and idk know why, but everything was different, now the variables are red and before it wasn't.

The persistent. variables are now half red half white. The screen atributes are with no theme, I don't have any screenshots from before but I think you guys got it.

![code](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/6ada50ef-2f7b-4c81-87a9-17a5816f4228)

I tried to use on my notebook after relising this and there it was normal, then again, I was required to reaload the studio and for the cience I did, and the colors was different again ;-;

Idk if someone can help me with this, and I now it sounds like nothing but I was with those colors for years and now they are just different.

(I am using "The Best Theme" theme, [link](https://marketplace.visualstudio.com/items?itemName=kohlbachjan.the-best-theme))

This is the first submit here so if was missing any info, my bad 🥲✌🏻

### Scope inspector screenshots

    frame:
        xysize(720, 720)
        background "gui/ui/background.png"
        foreground "gui/ui/foreground.png"
        xalign 0.5
        yalign 0.5

### Code

    frame:
        xysize(720, 720)
        background "gui/ui/background.png"
        foreground "gui/ui/foreground.png"
        xalign 0.5
        yalign 0.5

**Comment by LuqueDaniel** [comment]
Hi @JoaoGW7 . Today we have released a new version in which we use a new grammar, that's why now the variables have a different color. The color depends on the theme you are using.

**Comment by JoaoGW7** [comment]
> Hi @JoaoGW7 . Today we have released a new version in which we use a new grammar, that's why now the variables have a different color. The color depends on the theme you are using.

But how can I set like it was before? I tried to download the old version but nothing changed ;-; 
Also I didn't changed the theme or any setting.

**Comment by duckdoom4** [comment]
Can you post a screenshot of the half red issue you mentioned?

The highlighting of the frame block I will fix soon

**Comment by JoaoGW7** [comment]
> We'll try to fix the issue as soon as we can. With your help it will go even faster :)
> 
> Can you post a screenshot of the half red issue you mentioned?
> 
> The highlighting of the frame block I will fix soon

Sure 😄! Really thanks btw.

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/a7c8addb-19be-43de-afea-54c5e9b711c1)

Idk if I was clear about this before, but thats it.

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/4ee7e359-c28e-418b-87a6-c837bc94bb0f)

Another example about the screen atributes👆🏻

**Comment by duckdoom4** [comment]
Just to confirm, what is the color of a label in your label statements?

```label whats_my_color:```

**Comment by JoaoGW7** [comment]
Now they are blue:

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/a2ccf02d-b8fa-47a4-ad91-6e02f65e82b1)

Here are some screenshots I found from how it was BEFORE (they are from mouths ago, so I can't make a "before and after"):

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/f9adf61c-610d-42b3-ad9e-a0602d8890bd)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/31b8c59f-551d-4a6a-be7e-564210cf6bfe)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/8c7b0057-f12d-4cbd-bce5-ce2edd4ef5d2)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/62d6b818-2e16-4638-beaa-6afe573186d5)


And here are some more screenshots from hot it is NOW:

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/b1d097d6-2e7d-477e-93da-f1891a23ad22)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/68215d7a-0f17-4a78-8bac-7abcf18a514f)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/2ad2c1d5-fe52-4182-9de3-658fd844bf26)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/95ed1eb6-d620-4a68-ae40-8a2291972236)
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/74694445/49317410-6395-48a2-b682-93ba03722270)


I tried to send with similar codes. As you can see, just a bit different, but more then I would handle ;-;

Also, thanks for the fast answer, and sorry for anything 😄✌🏻🇧🇷

**Comment by duckdoom4** [comment]
Ah, I see what's going on there. I'll get those fixed too. Not sure if I have time to fix them all today, but I'll fix them ASAP

**Comment by duckdoom4** [comment]
Fix is on the way. Once it's merged and @LuqueDaniel has made a new build, it should be available to you. Please let me know if you have any additional issues with that new version

**Comment by Savage1969** [comment]
Will this new "fix" resolve the issue in code when {size=-xx} is used? Currently using the size text tag with a negative value causes the color to whack out as if there was a missing quotation mark on standard text. Regards.

**Comment by duckdoom4** [comment]
> Will this new "fix" resolve the new borked issue in code when {size=-xx} is used? Currently using the size text tag with a negative value causes the color to whack out as if there was a missing quotation mark on standard text. Regards.

Yes, it should

**Comment by JoaoGW7** [comment]
Updated it again and it is much better now, really thanks bros. The colors isnt the same as before but I think I can fix it 😁😁😁

Thanks bros, amazing work S2

**Comment by duckdoom4** [comment]
> Updated it again and it is much better now, really thanks bros. The colors isnt the same as before but I think I can fix it 😁😁😁
> 
> Thanks bros, amazing work S2

Could you tell me what you currently dislike about the color scheme? We made most changes to the color theme to improve readability and context.

Any feedback is welcome, it might improve the experience for everyone :)

**Comment by duckdoom4** [comment]
Hi there, I added highlighting for these keywords.
Though please note that screen language was kinda hacked in to get it sort of working.

I hope this will be a much better experience for you. Let me know if there are any other issues.
