### ISSUE TITLE
Old issue #180/#204 has resurfaced - Infinate "Initializing Ren'Py static data..."

### ISSUE THREAD

**Issue by Savage1969** [LuqueDaniel/vscode-language-renpy#332]
I searched and did not find this issue open in the current build. This was resolved in the past but has suddenly resurfaced in every project. Please advise.

**Edit**: This issue is the occurrence when opening a project outside of the SDK (which many of us do). 
**Edit2**: Now that 2.3.1 was pushed it does this in the SDK as well. It's completely broken now and causes other issues such as "Find in Files" impossible since the process never ends.

If this is a duplicate of a currently reported issue I didn't notice then please move this where appropriate. Regards.

**Comment by duckdoom4** [comment]
I'll look into it tomorrow, I remember some having this issue on the development branch but not on the main branch. Might be a configuration issue.

**Comment by duckdoom4** [comment]
Would you be able to compile a minimal project where this issue occurs? Easiest is probably grabbing a copy of a project that is broken and stripping everything that you don't want to upload. (You can also send me the zip file privately is that's preferred)

Having a project where it fails will help me figure out the issue much faster than going at this blind

**Comment by duckdoom4** [comment]
Hi there, I made a new build (v2.3.2). I added a logging output category for the extension to hopefully get some answers about what is going on here. 
Could you please post the log from the project you're having issues with? You can find it here:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/60387522/32a38e92-5ff3-40ca-8c52-5e08eafbdd79)

**Comment by Savage1969** [comment]
> Hi there, I made a new build (v2.3.2). I added a logging output category for the extension to hopefully get some answers about what is going on here. Could you please post the log from the project you're having issues with? You can find it here: ![image](https://user-images.githubusercontent.com/60387522/244102301-32a38e92-5ff3-40ca-8c52-5e08eafbdd79.png)

Apologies for the late reply, I did not see your new post. Otherwise I do not have that category available to me:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/049ed6a0-44ae-4907-8214-3788aa3b394d)

**Comment by LuqueDaniel** [comment]
@Savage1969 Are you using the pre-release version?

**Comment by duckdoom4** [comment]
Sounds to me like the extension is crashing which is causing all the issues. Basically once it crashes it will not do anything.

**Comment by Savage1969** [comment]
> I'm running into the same issue. Infinite "Initializing Ren'Py static data..."
> 
> The pop up below flashes for a split second (sorry for the screen grab quality, had to use my phone camera since it was flashing too fast):
> 
Dollars to doughnuts if you revert back to v2.1.7 you won't get the static data build issue. Test that and confirm. To do this (if you don't know), click the drop arrow next to "uninstall" (to open the context menu) and select "Install Another Version".
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/dc955a2a-398f-402a-95a8-4e3da301cf4e)

**Comment by duckdoom4** [comment]
Please try v2.3.4 this issue is likely fixed in that build :)

**Comment by Savage1969** [comment]
@duckdoom4 ... it took a long time to build (in the project I have open which is huge) and I almost gave up after a few minutes but it finally completed:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/22a0e88b-d81d-4a82-9f0e-6443d807e776)

That's with v2.3.4 which, since VSC could now finish it's init phase has seemed to cure many of the other extensions that were displaying as failed as well (I haven't check them all yet though).

Thank you. I can now hopefully work once again without the massive struggle that was starting to impede my deadlines. Brilliant work sir. Please don't forget this secret sauce for the next major update (j/k).

You can close the issue if you wish but maybe give us 24hrs or so to insure it's all okay. Again, I've only tested on one project at the moment.

**Comment by duckdoom4** [comment]
Alright, I'll close it. You can always reopen the issue if something else pops up
