### ISSUE TITLE
Support Named Stores for autocompletion and semantic highlighting

### ISSUE THREAD

**Issue by rdurfee** [LuqueDaniel/vscode-language-renpy#38]
The extension should support other Named Stores as defined in https://www.renpy.org/dev-doc/html/python.html#other-named-stores

- Named Stores should appear in the 'store' autocomplete list
- Variables and functions defined in the named store should autocomplete 
- Hover should work for named store variables and functions
- Semantic highlighting should support names stores by highlighting variables correctly

**Comment by LuqueDaniel** [comment]
Since PR #40 was merged. Can I close this?

**Comment by rdurfee** [comment]
Yes, I’ll  go ahead and close it.
