### ISSUE TITLE
Incorrect syntax highlighting in comments

### ISSUE THREAD

**Issue by KiloOscarSix** [LuqueDaniel/vscode-language-renpy#44]
Variable highlighting overwrites comment highlighting

![image](https://user-images.githubusercontent.com/26691547/139078008-b74d2d33-0988-4406-ac3d-568bfc1ec41b.png)

**Comment by LuqueDaniel** [comment]
> 
> 
> Variable highlighting overwrites comment highlighting
> 
> ![image](https://user-images.githubusercontent.com/26691547/139078008-b74d2d33-0988-4406-ac3d-568bfc1ec41b.png)

I can't reproduce it. Maybe I'm overlooking something, can you provide me with an example project?

**Comment by LuqueDaniel** [comment]
> 
> 
> Adding to this, I've noticed `self` isn't a keyword blue like it used to be. Instead, it's the same colour as normal variables

You mean like Python syntax highlighting?

![imagen](https://user-images.githubusercontent.com/1286535/139535465-be3ca861-0225-4875-87ee-006c50359fba.png)

Ren'Py:

![imagen](https://user-images.githubusercontent.com/1286535/139535506-19627078-3130-45c8-acae-c228e5c2d961.png)

**Comment by rdurfee** [comment]
I have seen this happen in comments and docs in Python functions.
