### ISSUE TITLE
Incorrect parameter hints on inherited/child classes

### ISSUE THREAD

**Issue by KiloOscarSix** [LuqueDaniel/vscode-language-renpy#45]
![image](https://user-images.githubusercontent.com/26691547/139079085-5a938b45-f784-4549-b021-053afaf150bd.png)

![image](https://user-images.githubusercontent.com/26691547/139079110-76d6a2cb-b562-4238-82c9-7981ad613a87.png)

**Comment by rdurfee** [comment]
This was fixed in 2.0.3.
