### ISSUE TITLE
[BUG] - Class symbols don't recognize static constants

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#46]
![image](https://user-images.githubusercontent.com/22531674/139171606-66d5ef24-ea89-414f-87ea-8571a16f5b58.png)

While methods from the class show, the constant, `NEWLINE_MATCHER` isn't listed.

Additionally, inherited members are not listed (note the parent class comes from a python-package)

**Comment by rdurfee** [comment]
This was fixed in release 2.0.3.
