### ISSUE TITLE
Syntax highlighting: `self` isn't a keyword blue like it used to be. Instead, it's the same colour as normal variables

### ISSUE THREAD

**Issue by LuqueDaniel** [LuqueDaniel/vscode-language-renpy#47]
Adding to this, I've noticed `self` isn't a keyword blue like it used to be. Instead, it's the same colour as normal variables

_Originally posted by @multimokia in https://github.com/LuqueDaniel/vscode-language-renpy/issues/44#issuecomment-953514544_

**Comment by LuqueDaniel** [comment]
> 
> 
> Adding to this, I've noticed `self` isn't a keyword blue like it used to be. Instead, it's the same colour as normal variables

You mean like Python syntax highlighting?

![imagen](https://user-images.githubusercontent.com/1286535/139535465-be3ca861-0225-4875-87ee-006c50359fba.png)

Ren'Py:

![imagen](https://user-images.githubusercontent.com/1286535/139535506-19627078-3130-45c8-acae-c228e5c2d961.png)

**Comment by LuqueDaniel** [comment]
@multimokia I've been checking this. It seems that it's because the semantic provider converts the token `self` into a token of the type parameter. Of course `self` is a parameter of the method (Unless it's a static method).

https://github.com/LuqueDaniel/vscode-language-renpy/blob/89ef8d08eaa59eb31fbbc4dbc13a69907a1d6007/src/semantics.ts#L129-L139

@rdurfee Can we do something about it?

**Comment by multimokia** [comment]
> You mean like Python syntax highlighting?

Python syntax highlighting never looked like that for me. Rather like:
![image](https://user-images.githubusercontent.com/22531674/139556768-1f4a8e0a-9f5d-4f0b-b055-d8b06b6d72f2.png)

I found a reference of this noted here: https://github.com/microsoft/vscode/issues/118946

I think potentially making it togglable might be best if possible? Personally I prefer having `self` and `cls` highlighted with the keyword color, it's also consistent with other languages like Java/C#/JS/TS/etc. where `this` is highlighted under the same color too.

**Comment by LuqueDaniel** [comment]
> 
> 
> Python syntax highlighting never looked like that for me. Rather like

It looks like it was a mistake, sorry.

![imagen](https://user-images.githubusercontent.com/1286535/139557007-fe76875b-c2c6-405d-a6d4-60002f3bf4a8.png)

**Comment by rdurfee** [comment]
That should be easy enough to fix. I would just need to make the token type _keyword_ instead of _parameter_. But I’m not sure if that’s the right behavior? It doesn’t seem to highlight that way in Python scripts?

**Comment by multimokia** [comment]
I'm not sure, in all my python scripts `self` is blue, I think the change was made in a later version of pylance, but I don't think it makes sense as `self` isn't really a variable, but it _is_ a keyword, representing the current instance. I noticed issues filed in the VSCode repo for it. But as mentioned before, being like `this`, it makes sense to have it use a keyword

**Comment by Booplicate** [comment]
I'll say that `self` and `cls` should be highlighted like keywords (deep blue). It's easier to read since those are special, standardised names. Furthermore, it is highlighted in the py extension (from ~2.6 to 3.7+)
![Capture](https://user-images.githubusercontent.com/53382877/139612951-59c9a3cd-2eee-4d75-b6a0-d6d7c6b0ffee.PNG)
