### ISSUE TITLE
[Feature Request] - Allow disabling of the reserved filename rule in workspaces

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#54]
![image](https://user-images.githubusercontent.com/22531674/140658421-20ae2937-8073-4f9b-bc1d-be125f480ca0.png)
When looking through renpy source files, all of the rpy files renpy has are filled with errors, it'd be nice to disable the behaviour for workspaces so one can dig through renpy source without the entire file reporting as an error due to the reserved filename

**Comment by rdurfee** [comment]
You can try adding the setting to your workspace settings file:
`"renpy.warnOnInvalidFilenameIssues": "Disabled"`

**Comment by multimokia** [comment]
Ah, totally missed that. My bad
