### ISSUE TITLE
Ren'Py keywords highlighted inside Python block

### ISSUE THREAD

**Issue by ghost** [LuqueDaniel/vscode-language-renpy#6]
Hi,

While having this extension enabled, keywords used by Ren'Py and the screen language get highlighted inside Python blocks.

With the extension disabled:
![image](https://user-images.githubusercontent.com/44584436/80954347-7fe24900-8dfd-11ea-9f7c-1baa294e4005.png)

With the extension enabled:
![image](https://user-images.githubusercontent.com/44584436/80954381-8c66a180-8dfd-11ea-9974-e362a9f03156.png)

**Comment by Tristimdorion** [comment]
As an addition to this request, how about parsing Python blocks using a python language linter and access to python keyword / language syntax.
