### ISSUE TITLE
[Feature Request] Ability to fold if statements, menu etc in the editor

### ISSUE THREAD

**Issue by Niv-Mizzet-lab** [LuqueDaniel/vscode-language-renpy#66]
Hi there,
I recently upgraded from 1.1.0 to 2.0.5.
Overall it's way nicer, but I miss the ability to fold almost everything that was indented.
For reference, here is a picture from 1.1.0
![1 1 0](https://user-images.githubusercontent.com/89451707/148598003-17f48d19-82cf-4b82-8465-362cb14b2337.JPG)
and one from 2.0.5
![2 0 5](https://user-images.githubusercontent.com/89451707/148598102-65986356-e43b-4581-8b40-a592d197cf3d.JPG)
In 2.0.5 I can only fold the label and nothing else in it.
I gave it a shot and dug through the code a little. As I understand it (keep in mind that I do not understand typescript or regex), the strings that the extension is using for folding are in the `const rxFolding` variable. I changed it to this,
`    const rxFolding = /^\s*(screen|label|class|layeredimage|def|init|if|elif|else|menu)\s+([a-zA-Z0-9_.]+)\((.*)\)\s*:|^\s*(screen|label|class|layeredimage|def|init|if|elif|else|menu)\s+([a-zA-Z0-9_.]+)\s*:/;` just to mess around and now it gives me this:
![Capture](https://user-images.githubusercontent.com/89451707/148599439-feac4f8f-0920-4954-84e1-af992a0f9762.JPG)
The ifs are found and it misses the else and the menu. I think it has something to do with the regular expression, but I cannot pinpoint it.

I don't expect it to be fixed tbh, but could someone that knows what they're doing please just point me to the right direction (assuming it's feasible)?

**Comment by LuqueDaniel** [comment]
Thanks. I'll take a look at it
