### ISSUE TITLE
Do we really need the folding provider?

### ISSUE THREAD

**Issue by LuqueDaniel** [LuqueDaniel/vscode-language-renpy#69]
While working on PR #68, the following question has come to my mind: Do we really need to apply our own rules for folding?

According to the [VSCode documentation](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding), there are two ways to define holding:

>In VS Code, folding is defined either `indentation-based`, or defined by contributed folding range providers:
>* Indentation-based folding with markers: If no folding range provider is available for the given language or if the user has set `editor.foldingStrategy` to `indentation`, indentation-based folding is used. A folding region starts when a line has a smaller indent than one or more following lines and ends when there is a line with the same or smaller indent. Empty lines are ignored. Additionally, the language configuration can define `start` and `end` markers. These are defined as start and end regexes in `folding.markers`. When matching lines are found, a folding range inside the pair is created. Folding markers must be non-empty and typically look like `//#region` and `//#endregion`.
>* Language server folding: The Language Server responds to the `textDocument/foldingRange` request with a list of folding ranges, and VS Code would render the ranges as folding markers. Learn more about the folding support in Language Server Protocol at the [Programmatic Language Feature](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) topic.

Since both Python and Ren'Py use indentation in the code blocks, what is the need to define it through the provider?

### Indentation

![imagen](https://user-images.githubusercontent.com/1286535/151669984-454cfe62-6c11-48b3-a3af-019614c4a3fa.png)
![imagen](https://user-images.githubusercontent.com/1286535/151670036-d095de88-3e4d-4df7-887f-fb38d964d2fd.png)
![imagen](https://user-images.githubusercontent.com/1286535/151670478-cbaa1948-026c-4992-98a2-5954153b6634.png)

### Provider

![imagen](https://user-images.githubusercontent.com/1286535/151670579-3c4bd495-46bc-4207-b248-4bcff0c7abc4.png)
![imagen](https://user-images.githubusercontent.com/1286535/151670560-e6f35991-cbc4-4623-b4d2-ac528e81c336.png)
![imagen](https://user-images.githubusercontent.com/1286535/151670520-62337e90-fba7-47a0-adc3-95abf4a9390a.png)

What is your opinion about this?

**Comment by rdurfee** [comment]
I think you might be right. Indentation based folding does seem the way to go here.
