### ISSUE TITLE
Please consider publishing this extension to Open VSX

### ISSUE THREAD

**Issue by GimmiRuski** [LuqueDaniel/vscode-language-renpy#7]
[VSCodium](https://github.com/VSCodium/vscodium) has switched to [Open VSX](https://github.com/eclipse/openvsx) as their extension gallery.

Please consider publishing this extension to Open VSX following [these steps](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by godofgrunts** [comment]
Second for this request.

**Comment by LuqueDaniel** [comment]
Ok, I'll check it soon!

**Comment by LuqueDaniel** [comment]
Done, thank you all!

https://open-vsx.org/extension/LuqueDaniel/languague-renpy

**Comment by TheDarkThief** [comment]
The older Ren'Py 8.2 version is there but not the newer Ren'Py 8.3 version, could you publish it please :pray:
