### ISSUE TITLE
Support annotations

### ISSUE THREAD

**Issue by Booplicate** [LuqueDaniel/vscode-language-renpy#71]
Hello! As we're getting closer to finally being able to use Python 3+, any plans to update the regex to account for new syntax like annotations? Right now it breaks the highlighting, so can't use the extension at all.

One example:
![Capture](https://user-images.githubusercontent.com/53382877/153794360-0b59d607-9d29-44d8-a90f-3d035e6f973c.PNG)

**Comment by JelleInfinity** [comment]
Fixed as of v2.1.0-pre-release
