### ISSUE TITLE
Support python 3 syntax

### ISSUE THREAD

**Issue by multimokia** [LuqueDaniel/vscode-language-renpy#75]
Given the release of renpy 8 nightly, we now have python 3 at our disposal meaning some new syntaxes to take care of

#71 already covers type annotations, but there's also some more such as f-strings, among others.

Would love to see this supported

**Comment by LuqueDaniel** [comment]
This is certainly something we need to implement. Right now both Ren'Py and Python syntax highlighting are defined in the `syntaxes/renpy.tmLanguage.json` file. The first thing will be to collect the syntax changes and write examples to validate the changes.

So far my experience editing that file hasn't been very good, so I'll have to study it from start to finish.

**Comment by multimokia** [comment]
Yeah it's a bit of a tricky one to edit given it's all regex strings unescaped. It's kinda difficult to follow.

That said I'm wondering if it's possible to leverage semantic highlighting for it via a parser. It may potentially be easier especially if we actually want to make type annotations functional like the standard python extension where hovering over a variable will also note its type.

**Comment by LuqueDaniel** [comment]
A good approach may be to handle Python syntax as an [embedded language](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages), especially now that Ren'Py is going to support Python 3. This way we would only have to worry about maintaining the Ren'Py syntax.

**Comment by multimokia** [comment]
I think this would make the most sense. Makes it a lot easier on our part then. My main concern is also the hover provider in this plugin to respect the type annotations as well

**Comment by multimokia** [comment]
It'd also massively clean up the syntaxes json since right now it seems to cover a mix of both renpy and python syntaxes, and as well it may just wind up fixing #6 if we split python handling to be separate?

**Comment by LuqueDaniel** [comment]
> It'd also massively clean up the syntaxes json since right now it seems to cover a mix of both renpy and python syntaxes, and as well it may just wind up fixing #6 if we split python handling to be separate?

I think it would solve it because it would apply only the Python syntax to that scope.

**Comment by LuqueDaniel** [comment]
In my spare time, I've started to rewrite the grammar. At the moment I've reimplemented the Python statements, using `source.renpy` (the grammar of the Python extension of VSCode). This way we will only have to implement and maintain Ren'Py specific syntax.

![imagen](https://user-images.githubusercontent.com/1286535/157281669-fe4c8dcb-264a-4e96-94f2-27c5f5f3c3d1.png)
![imagen](https://user-images.githubusercontent.com/1286535/157281827-03c6cc68-afc0-4217-abcc-26f328d5c011.png)
![imagen](https://user-images.githubusercontent.com/1286535/157282132-39105d8f-22d1-4ec1-80e5-95efb17bcf11.png)

There is still a long way to go, but if you want to try it, you can do it with PR #76. Contributions, feedback, and bug reports are welcome!

**Comment by multimokia** [comment]
Amazing, I'll definitely pull this!

**Comment by LuqueDaniel** [comment]
@Elckarow Thank you. It's already fixed in `new-syntax` branch. But support for type hint has yet to be added to other features.

**Comment by JelleInfinity** [comment]
Fixed as of v2.1.0-pre-release
