### ISSUE TITLE
`Visual Studio Code.edit.py` blows up paths with spaces in them

### ISSUE THREAD

**Issue by coldacid** [LuqueDaniel/vscode-language-renpy#79]
I'm not sure if this is an issue with the editor script or if it's a problem with Ren'Py itself, but it makes things a bit frustrating when working from the launcher.

**Comment by LuqueDaniel** [comment]
Can you provide more information? OS and error log.

**Comment by LuqueDaniel** [comment]
Can you provide more information? OS and error log.

**Comment by LuqueDaniel** [comment]
@coldacid can you test #80?

**Comment by coldacid** [comment]
@LuqueDaniel works!
