### ISSUE TITLE
Refresh images autocompletion when adding/removing files

### ISSUE THREAD

**Issue by Cronos87** [LuqueDaniel/vscode-language-renpy#91]
Hi!

It appears that the autocompletion when typing `scene` or `with` is not showing the images in the images directory, not until I refresh VSCode. Then if I add/remove a file, the autocompletion remembers the completion before the modification.

Maybe I'm using it wrong. Let me know.

Thank you in advance!

**Comment by JelleInfinity** [comment]
That's caused by a bug that I submitted a [pull request](https://github.com/LuqueDaniel/vscode-language-renpy/pull/98) for yesterday. Should be fixed when merged and updated.
